### ISSUE TITLE
[BUG] Asset Pipeline fails if the textures are located in a subfolder

### ISSUE THREAD

**Issue by andreagalle** [Toontown-Event-Horizon/panda-utils#3]
### Operating system

Windows

### Output of `pip freeze`

```numpy==1.24.4
panda-utils==1.6b4
Panda3D==1.10.12
panda3d-blend2bam==0.23.0
panda3d-gltf==1.0.1
panda3d-simplepbr==0.10
PyYAML==6.0.1
```

### Blender Version

3.6.5

### What happened?

I am trying to import an `.obj` file into the pipeline, to get an `.egg` file with all the relative textures. What I am concerned baout is that the pipeline itself seems to lose the textures, while blender (although throwns exactly the same WARNING at the very beginning) finally seems to recover these textures, someway.

Thus, I set the following DEBUG env variable: `PANDA_UTILS_DEBUG = 'all'`

Here below the relevant pipeline logs:

```
(panda3D) PS C:\Users\andrea\Documents\tiber-river\walkintiber\thegame\asset_pipeline> python -m panda_utils.assetpipeline input/buildings-test test/models/buildings test/maps preblend blend2bam bam2egg egg2bam
panda_utils.pipeline: INFO     Running Pipeline with parameters: ['preblend', 'blend2bam', 'bam2egg', 'egg2bam']
panda_utils.converter.blender: INFO     Buildings Test: Converting to blend: test4_buildings.obj, test4_buildings.obj.mtl, test4_buildings.obj_textures
Blender 3.6.5 (hash cf1e1ed46b7e built 2023-10-19 01:09:47)
Read prefs: "C:\Users\andrea\AppData\Roaming\Blender Foundation\Blender\3.6\config\userpref.blend"
WARN (bgl): C:\Users\blender\git\blender-v360\blender.git\source\blender\python\generic\bgl.c:2662 BPyInit_bgl: 'bgl' imported without an OpenGL backend. Please update your add-ons to use the 'gpu' module. In Blender 4.0 'bgl' will be removed.
DEBUG:BlenderGIS-master.core.checkdeps:GDAL Python binding unavailable
DEBUG:BlenderGIS-master.core.checkdeps:PyProj available
DEBUG:BlenderGIS-master.core.checkdeps:Pillow available
DEBUG:BlenderGIS-master.core.checkdeps:ImageIO Freeimage plugin available
blenderkit addon: Verbose is enabled
blenderkit addon: Read in JSON settings from file
(  0.0000 sec |   0.0000 sec) Importing OBJ 'test4_buildings.obj'...
  (  0.0182 sec |   0.0182 sec) Parsing OBJ file...
    (  0.1263 sec |   0.1081 sec) Done, loading materials and images...
WARNING, currently unsupported ambient texture, skipped.
WARNING, currently unsupported ambient texture, skipped.
WARNING, currently unsupported ambient texture, skipped.
WARNING, currently unsupported ambient texture, skipped.
WARNING, currently unsupported ambient texture, skipped.
    (  0.1860 sec |   0.1677 sec) Done, building geometries (verts:2238 faces:3704 materials: 5 smoothgroups:0) ...
    (  0.3577 sec |   0.3395 sec) Done.
  (  0.3577 sec |   0.3577 sec) Finished importing: 'test4_buildings.obj'
Progress: 100.00%

Info: Total files 4 | Changed 4 | Failed 0
Info: Saved "buildings-test.blend"
blenderkit INFO: Unregistering BlenderKit add-on [17:02:49.478, __init__.py:2393]
blenderkit INFO: Reported Blender quit to daemon [17:02:49.496, __init__.py:2413]

Blender quit
panda_utils.converter.blender: INFO     Buildings Test: Exporting to GLTF: buildings-test.blend
Blender 3.6.5 (hash cf1e1ed46b7e built 2023-10-19 01:09:47)
Read prefs: "C:\Users\andrea\AppData\Roaming\Blender Foundation\Blender\3.6\config\userpref.blend"
WARN (bgl): C:\Users\blender\git\blender-v360\blender.git\source\blender\python\generic\bgl.c:2662 BPyInit_bgl: 'bgl' imported without an OpenGL backend. Please update your add-ons to use the 'gpu' module. In Blender 4.0 'bgl' will be removed.
DEBUG:BlenderGIS-master.core.checkdeps:GDAL Python binding unavailable
DEBUG:BlenderGIS-master.core.checkdeps:PyProj available
DEBUG:BlenderGIS-master.core.checkdeps:Pillow available
DEBUG:BlenderGIS-master.core.checkdeps:ImageIO Freeimage plugin available
blenderkit addon: Verbose is enabled
blenderkit addon: Read in JSON settings from file
Read blend: "C:\Users\andrea\Documents\tiber-river\walkintiber\thegame\asset_pipeline\intermediate\test__models__buildings__buildings-test\buildings-test.blend"
16:02:55 | INFO: Draco mesh compression is available, use library at C:\Program Files\Blender Foundation\Blender 3.6\3.6\python\lib\site-packages\extern_draco.dll
16:02:55 | INFO: Starting glTF 2.0 export
16:02:55 | INFO: Extracting primitive: Building0
16:02:55 | INFO: Primitives created: 2
16:02:55 | INFO: Extracting primitive: Building Palazzo Orsini
16:02:55 | INFO: Primitives created: 2
16:02:55 | INFO: Extracting primitive: Building Tempio Maggiore di Roma
16:02:55 | INFO: Primitives created: 2

...

16:02:56 | INFO: Finished glTF 2.0 export in 0.747887134552002 s

blenderkit INFO: Unregistering BlenderKit add-on [17:02:56.331, __init__.py:2393]
blenderkit INFO: Reported Blender quit to daemon [17:02:56.332, __init__.py:2413]
Blender quit
panda_utils.converter.blender: INFO     Buildings Test: Converting to bam: buildings-test.glb
panda_utils.pipeline.models: INFO     Buildings Test: Converting buildings-test.bam from Bam to Egg
Writing buildings-test.egg

panda_utils.converter: INFO     Recompilation not needed!
panda_utils.pipeline.models: INFO     Buildings Test: Copying buildings-test.egg into the dist directory
panda_utils.pipeline.models: INFO     Buildings Test: Converting buildings-test.egg to bam
panda_utils.palettize: WARNING
Writing test/models/buildings/buildings-test.bam

(panda3D) PS C:\Users\andrea\Documents\tiber-river\walkintiber\thegame\asset_pipeline> bam2egg .\built\test\models\buildings\buildings-test.bam pp-test.egg

./built/test/models/buildings/buildings-test.bam : Bam version 6.44
Writing pp-test.egg
```

Against the corresponding blender logs:

```
(  0.0000 sec |   0.0000 sec) Importing OBJ 'C:\\Users\\andrea\\Documents\\tiber-river\\walkintiber\\thegame\\asset_pipeline\\input\\buildings-test\\test4_buildings.obj'...
  (  0.0000 sec |   0.0000 sec) Parsing OBJ file...
    (  0.0468 sec |   0.0468 sec) Done, loading materials and images...
WARNING, currently unsupported ambient texture, skipped.
WARNING, currently unsupported ambient texture, skipped.
WARNING, currently unsupported ambient texture, skipped.
WARNING, currently unsupported ambient texture, skipped.
WARNING, currently unsupported ambient texture, skipped.
    (  0.0624 sec |   0.0624 sec) Done, building geometries (verts:2238 faces:3704 materials: 5 smoothgroups:0) ...
    (  0.1874 sec |   0.1874 sec) Done.
  (  0.1874 sec |   0.1874 sec) Finished importing: 'C:\\Users\\andrea\\Documents\\tiber-river\\walkintiber\\thegame\\asset_pipeline\\input\\buildings-test\\test4_buildings.obj'
Progress: 100.00%

Objects for export: ['Building0', 'Building Palazzo Orsini', 'Building Tempio Maggiore di Roma', 'Building1', 'Building2', 'Building3', 'Building4', 'Building Fatebenefratelli', 'Building Palazzo dellAnagrafe', 'Building5', 'Building6', 'Building7', 'Building8', 'Building9', 'Building10', 'Building11', 'Building12', 'Building13', 'Building14', 'Building15', 'Building16', 'Building17', 'Building18', 'Building19', 'Building20', 'Building21', 'Building22', 'Building23', 'Building24', 'Building25', 'Building26', 'Building27', 'Building28', 'Building29', 'Building Teatro Belli', 'Building30', 'Building31', 'Building32', 'Building33', 'Building34', 'Building35', 'Building36', 'Building37', 'Building38', 'Building39', 'Building40', 'Building41', 'Building42', 'Building43', 'Building44', 'Building45', 'Building46', 'Building47', 'Building48', 'Building49', 'Building50', 'Building51', 'Building52', 'Building53', 'Building54', 'Building55', 'Building56', 'Building57', 'Building John Cabot University - Tiber Campus', 'Building58', 'Building59', 'Building60', 'Building61', 'Building62', 'Building63', 'Building64', 'Building65', 'Building66', 'Building67', 'Building68', 'Building69', 'Building70', 'Building Pizza Trilussa', 'Building71', 'Building72', 'Building73', 'Building74', 'Building75', 'Building76', 'Building77', 'Building78', 'Building79', 'Building80', 'Building81', 'Building82', 'Building83', 'Building84', 'Building85', 'Building86', 'Building87', 'Building88', 'Building89', 'Building90', 'Building Ospedale Israelitico Roma', 'Building Torre Caetani', 'Building91', 'Building Teatro di Marcello', 'Building92', 'Building Chiesa di San Nicola in Carcere', 'Building Chiesa di San Giovanni Calibita', 'Building93', 'Building94', 'Building95', 'Building96', 'Building97', 'Building98', 'Building99', 'Building Basilica di San Bartolomeo allIsola', 'Building100', 'Building101', 'Building102', 'Building103', 'Building104', 'Building105', 'Building106', 'Building107', 'Building108', 'Building Grattacheccaro Alla Fonte dOro', 'Building109', 'Building110', 'Building111', 'Building112', 'Building113', 'Building114', 'Building115', 'Building116', 'Building117', 'Building118', 'Building119', 'Building120', 'Building121', 'Building Chiesa di San Gregorio della Divina Pieta', 'SurfaceArea122', 'SurfaceArea123', 'SurfaceArea124']
WRITE main EGG to C:\Users\andrea\Documents\tiber-river\walkintiber\thegame\test.egg
INFO: Used materials:  {'TERRAIN_DEFAULT_0', 'MAT_1_0', 'BUILDING_DEFAULT_0', 'ROOF_DEFAULT_0', 'MAT_1_1'}
Found Panda3D compatible Principled BSDF shader. Collecting PBR textures
[bpy.data.objects['Building0.001'], bpy.data.objects['Building Palazzo Orsini.001'], bpy.data.objects['Building Tempio Maggiore di Roma.001'], bpy.data.objects['Building1.001'], bpy.data.objects['Building2.001'], bpy.data.objects['Building3.001'], bpy.data.objects['Building4.001'], bpy.data.objects['Building Fatebenefratelli.001'], bpy.data.objects['Building Palazzo dellAnagrafe.001'], bpy.data.objects['Building5.001'], bpy.data.objects['Building6.001'], bpy.data.objects['Building7.001'], bpy.data.objects['Building8.001'], bpy.data.objects['Building9.001'], bpy.data.objects['Building10.001'], bpy.data.objects['Building11.001'], bpy.data.objects['Building12.001'], bpy.data.objects['Building13.001'], bpy.data.objects['Building14.001'], bpy.data.objects['Building15.001'], bpy.data.objects['Building16.001'], bpy.data.objects['Building17.001'], bpy.data.objects['Building18.001'], bpy.data.objects['Building19.001'], bpy.data.objects['Building20.001'], bpy.data.objects['Building21.001'], bpy.data.objects['Building22.001'], bpy.data.objects['Building23.001'], bpy.data.objects['Building24.001'], bpy.data.objects['Building25.001'], bpy.data.objects['Building26.001'], bpy.data.objects['Building27.001'], bpy.data.objects['Building28.001'], bpy.data.objects['Building29.001'], bpy.data.objects['Building Teatro Belli.001'], bpy.data.objects['Building30.001'], bpy.data.objects['Building31.001'], bpy.data.objects['Building32.001'], bpy.data.objects['Building33.001'], bpy.data.objects['Building34.001'], bpy.data.objects['Building35.001'], bpy.data.objects['Building36.001'], bpy.data.objects['Building37.001'], bpy.data.objects['Building38.001'], bpy.data.objects['Building39.001'], bpy.data.objects['Building40.001'], bpy.data.objects['Building41.001'], bpy.data.objects['Building42.001'], bpy.data.objects['Building43.001'], bpy.data.objects['Building44.001'], bpy.data.objects['Building45.001'], bpy.data.objects['Building46.001'], bpy.data.objects['Building47.001'], bpy.data.objects['Building48.001'], bpy.data.objects['Building49.001'], bpy.data.objects['Building50.001'], bpy.data.objects['Building51.001'], bpy.data.objects['Building52.001'], bpy.data.objects['Building53.001'], bpy.data.objects['Building54.001'], bpy.data.objects['Building55.001'], bpy.data.objects['Building56.001'], bpy.data.objects['Building57.001'], bpy.data.objects['Building John Cabot University - Tiber Campus.001'], bpy.data.objects['Building58.001'], bpy.data.objects['Building59.001'], bpy.data.objects['Building60.001'], bpy.data.objects['Building61.001'], bpy.data.objects['Building62.001'], bpy.data.objects['Building63.001'], bpy.data.objects['Building64.001'], bpy.data.objects['Building65.001'], bpy.data.objects['Building66.001'], bpy.data.objects['Building67.001'], bpy.data.objects['Building68.001'], bpy.data.objects['Building69.001'], bpy.data.objects['Building70.001'], bpy.data.objects['Building Pizza Trilussa.001'], bpy.data.objects['Building71.001'], bpy.data.objects['Building72.001'], bpy.data.objects['Building73.001'], bpy.data.objects['Building74.001'], bpy.data.objects['Building75.001'], bpy.data.objects['Building76.001'], bpy.data.objects['Building77.001'], bpy.data.objects['Building78.001'], bpy.data.objects['Building79.001'], bpy.data.objects['Building80.001'], bpy.data.objects['Building81.001'], bpy.data.objects['Building82.001'], bpy.data.objects['Building83.001'], bpy.data.objects['Building84.001'], bpy.data.objects['Building85.001'], bpy.data.objects['Building86.001'], bpy.data.objects['Building87.001'], bpy.data.objects['Building88.001'], bpy.data.objects['Building89.001'], bpy.data.objects['Building90.001'], bpy.data.objects['Building Ospedale Israelitico Roma.001'], bpy.data.objects['Building Torre Caetani.001'], bpy.data.objects['Building91.001'], bpy.data.objects['Building Teatro di Marcello.001'], bpy.data.objects['Building92.001'], bpy.data.objects['Building Chiesa di San Nicola in Carcere.001'], bpy.data.objects['Building Chiesa di San Giovanni Calibita.001'], bpy.data.objects['Building93.001'], bpy.data.objects['Building94.001'], bpy.data.objects['Building95.001'], bpy.data.objects['Building96.001'], bpy.data.objects['Building97.001'], bpy.data.objects['Building98.001'], bpy.data.objects['Building99.001'], bpy.data.objects['Building Basilica di San Bartolomeo allIsola.001'], bpy.data.objects['Building100.001'], bpy.data.objects['Building101.001'], bpy.data.objects['Building102.001'], bpy.data.objects['Building103.001'], bpy.data.objects['Building104.001'], bpy.data.objects['Building105.001'], bpy.data.objects['Building106.001'], bpy.data.objects['Building107.001'], bpy.data.objects['Building108.001'], bpy.data.objects['Building Grattacheccaro Alla Fonte dOro.001'], bpy.data.objects['Building109.001'], bpy.data.objects['Building110.001'], bpy.data.objects['Building111.001'], bpy.data.objects['Building112.001'], bpy.data.objects['Building113.001'], bpy.data.objects['Building114.001'], bpy.data.objects['Building115.001'], bpy.data.objects['Building116.001'], bpy.data.objects['Building117.001'], bpy.data.objects['Building118.001'], bpy.data.objects['Building119.001'], bpy.data.objects['Building120.001'], bpy.data.objects['Building121.001'], bpy.data.objects['Building Chiesa di San Gregorio della Divina Pieta.001'], bpy.data.objects['SurfaceArea122.001'], bpy.data.objects['SurfaceArea123.001'], bpy.data.objects['SurfaceArea124.001']]
Processing object <bpy_struct, Object("Building0.001") at 0x000002E756A80808>
INFO: Found the Panda3D compatible Principled BSDF shader
INFO: tex-Plaster002_Color-1175447457309335745.png node is renamed to tex-Plaster002_Color-1175447457309335745.png
WARNING: Texture has no UV-INPUT! Building0.001 Base Color
INFO: Adding UV Map from the material: Building0.001
DIR is not exist: Creating...  C:\Users\andrea\Documents\tiber-river\walkintiber\thegame\tex
Texture:  tex-Plaster002_Color-1175447457309335745.png
RENDER IMAGE to C:\Users\andrea\Documents\tiber-river\walkintiber\thegame\tex\tex-Plaster002_Color-1175447457309335745.png; rel path: ./tex/tex-Plaster002_Color-1175447457309335745.png
COPY IMAGE C:\Users\andrea\Documents\tiber-river\walkintiber\thegame\asset_pipeline\input\buildings-test\test4_buildings.obj_textures\tex-Plaster002_Color-1175447457309335745.png to C:\Users\andrea\Documents\tiber-river\walkintiber\thegame\tex\tex-Plaster002_Color-1175447457309335745.png; rel path ./tex/tex-Plaster002_Color-1175447457309335745.png
Traceback (most recent call last):
  File "C:\Users\andrea\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\PRPEE-master\yabee_libs\egg_writer.py", line 1669, in write_out
    materials_str, USED_MATERIALS, USED_TEXTURES = get_egg_materials_str(selected_obj)
  File "C:\Users\andrea\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\PRPEE-master\yabee_libs\egg_writer.py", line 1363, in get_egg_materials_str
    used_textures.update(pbrtex.get_used_textures())
  File "C:\Users\andrea\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\PRPEE-master\yabee_libs\texture_processor.py", line 148, in get_used_textures
    if hasattr(bpy.context.object.active_material, "blend_method"):
AttributeError: 'NoneType' object has no attribute 'active_material'
```

As you can see something happened in terms of textures here, and the `.egg` file does have textures in the game (because of the `tex` directory blender made here. 

### Used modules

- [ ] [Egg Tree Parser](https://panda-utils.readthedocs.io/en/latest/egg-trees/introduction.html)
- [X] [Asset Pipeline](https://panda-utils.readthedocs.io/en/latest/asset-pipeline/introduction.html)
- [ ] [Asset Composer](https://panda-utils.readthedocs.io/en/latest/asset-pipeline/composer.html)

### Pipeline Command and relevant Egg file

```
 python -m panda_utils.assetpipeline input/buildings-test test/models/buildings test/maps preblend blend2bam bam2egg egg2bam
 ```

**Comment by andreagalle** [comment]
I was still editing this! Wait a sec

**Comment by andreagalle** [comment]
### Operating system

Windows

### Output of `pip freeze`

```numpy==1.24.4
panda-utils==1.6b4
Panda3D==1.10.12
panda3d-blend2bam==0.23.0
panda3d-gltf==1.0.1
panda3d-simplepbr==0.10
PyYAML==6.0.1
```

### Blender Version

3.6.5

### What happened?

I am trying to import an `.obj` file into the pipeline, to get an `.egg` file with all the relative textures. What I am concerned baout is that the pipeline itself seems to lose the textures, while blender (although throwns exactly the same WARNING at the very beginning) finally seems to recover these textures, someway.

Thus, I set the following DEBUG env variable: `PANDA_UTILS_DEBUG = 'all'`

Here below the relevant pipeline logs:

```
(panda3D) PS C:\Users\andrea\Documents\tiber-river\walkintiber\thegame\asset_pipeline> python -m panda_utils.assetpipeline input/buildings-test test/models/buildings test/maps preblend blend2bam bam2egg egg2bam
panda_utils.pipeline: INFO     Running Pipeline with parameters: ['preblend', 'blend2bam', 'bam2egg', 'egg2bam']
panda_utils.converter.blender: INFO     Buildings Test: Converting to blend: test4_buildings.obj, test4_buildings.obj.mtl, test4_buildings.obj_textures
Blender 3.6.5 (hash cf1e1ed46b7e built 2023-10-19 01:09:47)
Read prefs: "C:\Users\andrea\AppData\Roaming\Blender Foundation\Blender\3.6\config\userpref.blend"
WARN (bgl): C:\Users\blender\git\blender-v360\blender.git\source\blender\python\generic\bgl.c:2662 BPyInit_bgl: 'bgl' imported without an OpenGL backend. Please update your add-ons to use the 'gpu' module. In Blender 4.0 'bgl' will be removed.
DEBUG:BlenderGIS-master.core.checkdeps:GDAL Python binding unavailable
DEBUG:BlenderGIS-master.core.checkdeps:PyProj available
DEBUG:BlenderGIS-master.core.checkdeps:Pillow available
DEBUG:BlenderGIS-master.core.checkdeps:ImageIO Freeimage plugin available
blenderkit addon: Verbose is enabled
blenderkit addon: Read in JSON settings from file
(  0.0000 sec |   0.0000 sec) Importing OBJ 'test4_buildings.obj'...
  (  0.0182 sec |   0.0182 sec) Parsing OBJ file...
    (  0.1263 sec |   0.1081 sec) Done, loading materials and images...
WARNING, currently unsupported ambient texture, skipped.
WARNING, currently unsupported ambient texture, skipped.
WARNING, currently unsupported ambient texture, skipped.
WARNING, currently unsupported ambient texture, skipped.
WARNING, currently unsupported ambient texture, skipped.
    (  0.1860 sec |   0.1677 sec) Done, building geometries (verts:2238 faces:3704 materials: 5 smoothgroups:0) ...
    (  0.3577 sec |   0.3395 sec) Done.
  (  0.3577 sec |   0.3577 sec) Finished importing: 'test4_buildings.obj'
Progress: 100.00%

Info: Total files 4 | Changed 4 | Failed 0
Info: Saved "buildings-test.blend"
blenderkit INFO: Unregistering BlenderKit add-on [17:02:49.478, __init__.py:2393]
blenderkit INFO: Reported Blender quit to daemon [17:02:49.496, __init__.py:2413]

Blender quit
panda_utils.converter.blender: INFO     Buildings Test: Exporting to GLTF: buildings-test.blend
Blender 3.6.5 (hash cf1e1ed46b7e built 2023-10-19 01:09:47)
Read prefs: "C:\Users\andrea\AppData\Roaming\Blender Foundation\Blender\3.6\config\userpref.blend"
WARN (bgl): C:\Users\blender\git\blender-v360\blender.git\source\blender\python\generic\bgl.c:2662 BPyInit_bgl: 'bgl' imported without an OpenGL backend. Please update your add-ons to use the 'gpu' module. In Blender 4.0 'bgl' will be removed.
DEBUG:BlenderGIS-master.core.checkdeps:GDAL Python binding unavailable
DEBUG:BlenderGIS-master.core.checkdeps:PyProj available
DEBUG:BlenderGIS-master.core.checkdeps:Pillow available
DEBUG:BlenderGIS-master.core.checkdeps:ImageIO Freeimage plugin available
blenderkit addon: Verbose is enabled
blenderkit addon: Read in JSON settings from file
Read blend: "C:\Users\andrea\Documents\tiber-river\walkintiber\thegame\asset_pipeline\intermediate\test__models__buildings__buildings-test\buildings-test.blend"
16:02:55 | INFO: Draco mesh compression is available, use library at C:\Program Files\Blender Foundation\Blender 3.6\3.6\python\lib\site-packages\extern_draco.dll
16:02:55 | INFO: Starting glTF 2.0 export
16:02:55 | INFO: Extracting primitive: Building0
16:02:55 | INFO: Primitives created: 2
16:02:55 | INFO: Extracting primitive: Building Palazzo Orsini
16:02:55 | INFO: Primitives created: 2
16:02:55 | INFO: Extracting primitive: Building Tempio Maggiore di Roma
16:02:55 | INFO: Primitives created: 2

...

16:02:56 | INFO: Finished glTF 2.0 export in 0.747887134552002 s

blenderkit INFO: Unregistering BlenderKit add-on [17:02:56.331, __init__.py:2393]
blenderkit INFO: Reported Blender quit to daemon [17:02:56.332, __init__.py:2413]
Blender quit
panda_utils.converter.blender: INFO     Buildings Test: Converting to bam: buildings-test.glb
panda_utils.pipeline.models: INFO     Buildings Test: Converting buildings-test.bam from Bam to Egg
Writing buildings-test.egg

panda_utils.converter: INFO     Recompilation not needed!
panda_utils.pipeline.models: INFO     Buildings Test: Copying buildings-test.egg into the dist directory
panda_utils.pipeline.models: INFO     Buildings Test: Converting buildings-test.egg to bam
panda_utils.palettize: WARNING
Writing test/models/buildings/buildings-test.bam

(panda3D) PS C:\Users\andrea\Documents\tiber-river\walkintiber\thegame\asset_pipeline> bam2egg .\built\test\models\buildings\buildings-test.bam pp-test.egg

./built/test/models/buildings/buildings-test.bam : Bam version 6.44
Writing pp-test.egg
```

Against the corresponding blender logs:

```
(  0.0000 sec |   0.0000 sec) Importing OBJ 'C:\\Users\\andrea\\Documents\\tiber-river\\walkintiber\\thegame\\asset_pipeline\\input\\buildings-test\\test4_buildings.obj'...
  (  0.0000 sec |   0.0000 sec) Parsing OBJ file...
    (  0.0468 sec |   0.0468 sec) Done, loading materials and images...
WARNING, currently unsupported ambient texture, skipped.
WARNING, currently unsupported ambient texture, skipped.
WARNING, currently unsupported ambient texture, skipped.
WARNING, currently unsupported ambient texture, skipped.
WARNING, currently unsupported ambient texture, skipped.
    (  0.0624 sec |   0.0624 sec) Done, building geometries (verts:2238 faces:3704 materials: 5 smoothgroups:0) ...
    (  0.1874 sec |   0.1874 sec) Done.
  (  0.1874 sec |   0.1874 sec) Finished importing: 'C:\\Users\\andrea\\Documents\\tiber-river\\walkintiber\\thegame\\asset_pipeline\\input\\buildings-test\\test4_buildings.obj'
Progress: 100.00%

Objects for export: ['Building0', 'Building Palazzo Orsini', 'Building Tempio Maggiore di Roma', 'Building1', 'Building2', 'Building3', 'Building4', 'Building Fatebenefratelli', 'Building Palazzo dellAnagrafe', 'Building5', 'Building6', 'Building7', 'Building8', 'Building9', 'Building10', 'Building11', 'Building12', 'Building13', 'Building14', 'Building15', 'Building16', 'Building17', 'Building18', 'Building19', 'Building20', 'Building21', 'Building22', 'Building23', 'Building24', 'Building25', 'Building26', 'Building27', 'Building28', 'Building29', 'Building Teatro Belli', 'Building30', 'Building31', 'Building32', 'Building33', 'Building34', 'Building35', 'Building36', 'Building37', 'Building38', 'Building39', 'Building40', 'Building41', 'Building42', 'Building43', 'Building44', 'Building45', 'Building46', 'Building47', 'Building48', 'Building49', 'Building50', 'Building51', 'Building52', 'Building53', 'Building54', 'Building55', 'Building56', 'Building57', 'Building John Cabot University - Tiber Campus', 'Building58', 'Building59', 'Building60', 'Building61', 'Building62', 'Building63', 'Building64', 'Building65', 'Building66', 'Building67', 'Building68', 'Building69', 'Building70', 'Building Pizza Trilussa', 'Building71', 'Building72', 'Building73', 'Building74', 'Building75', 'Building76', 'Building77', 'Building78', 'Building79', 'Building80', 'Building81', 'Building82', 'Building83', 'Building84', 'Building85', 'Building86', 'Building87', 'Building88', 'Building89', 'Building90', 'Building Ospedale Israelitico Roma', 'Building Torre Caetani', 'Building91', 'Building Teatro di Marcello', 'Building92', 'Building Chiesa di San Nicola in Carcere', 'Building Chiesa di San Giovanni Calibita', 'Building93', 'Building94', 'Building95', 'Building96', 'Building97', 'Building98', 'Building99', 'Building Basilica di San Bartolomeo allIsola', 'Building100', 'Building101', 'Building102', 'Building103', 'Building104', 'Building105', 'Building106', 'Building107', 'Building108', 'Building Grattacheccaro Alla Fonte dOro', 'Building109', 'Building110', 'Building111', 'Building112', 'Building113', 'Building114', 'Building115', 'Building116', 'Building117', 'Building118', 'Building119', 'Building120', 'Building121', 'Building Chiesa di San Gregorio della Divina Pieta', 'SurfaceArea122', 'SurfaceArea123', 'SurfaceArea124']
WRITE main EGG to C:\Users\andrea\Documents\tiber-river\walkintiber\thegame\test.egg
INFO: Used materials:  {'TERRAIN_DEFAULT_0', 'MAT_1_0', 'BUILDING_DEFAULT_0', 'ROOF_DEFAULT_0', 'MAT_1_1'}
Found Panda3D compatible Principled BSDF shader. Collecting PBR textures
[bpy.data.objects['Building0.001'], bpy.data.objects['Building Palazzo Orsini.001'], bpy.data.objects['Building Tempio Maggiore di Roma.001'], bpy.data.objects['Building1.001'], bpy.data.objects['Building2.001'], bpy.data.objects['Building3.001'], bpy.data.objects['Building4.001'], bpy.data.objects['Building Fatebenefratelli.001'], bpy.data.objects['Building Palazzo dellAnagrafe.001'], bpy.data.objects['Building5.001'], bpy.data.objects['Building6.001'], bpy.data.objects['Building7.001'], bpy.data.objects['Building8.001'], bpy.data.objects['Building9.001'], bpy.data.objects['Building10.001'], bpy.data.objects['Building11.001'], bpy.data.objects['Building12.001'], bpy.data.objects['Building13.001'], bpy.data.objects['Building14.001'], bpy.data.objects['Building15.001'], bpy.data.objects['Building16.001'], bpy.data.objects['Building17.001'], bpy.data.objects['Building18.001'], bpy.data.objects['Building19.001'], bpy.data.objects['Building20.001'], bpy.data.objects['Building21.001'], bpy.data.objects['Building22.001'], bpy.data.objects['Building23.001'], bpy.data.objects['Building24.001'], bpy.data.objects['Building25.001'], bpy.data.objects['Building26.001'], bpy.data.objects['Building27.001'], bpy.data.objects['Building28.001'], bpy.data.objects['Building29.001'], bpy.data.objects['Building Teatro Belli.001'], bpy.data.objects['Building30.001'], bpy.data.objects['Building31.001'], bpy.data.objects['Building32.001'], bpy.data.objects['Building33.001'], bpy.data.objects['Building34.001'], bpy.data.objects['Building35.001'], bpy.data.objects['Building36.001'], bpy.data.objects['Building37.001'], bpy.data.objects['Building38.001'], bpy.data.objects['Building39.001'], bpy.data.objects['Building40.001'], bpy.data.objects['Building41.001'], bpy.data.objects['Building42.001'], bpy.data.objects['Building43.001'], bpy.data.objects['Building44.001'], bpy.data.objects['Building45.001'], bpy.data.objects['Building46.001'], bpy.data.objects['Building47.001'], bpy.data.objects['Building48.001'], bpy.data.objects['Building49.001'], bpy.data.objects['Building50.001'], bpy.data.objects['Building51.001'], bpy.data.objects['Building52.001'], bpy.data.objects['Building53.001'], bpy.data.objects['Building54.001'], bpy.data.objects['Building55.001'], bpy.data.objects['Building56.001'], bpy.data.objects['Building57.001'], bpy.data.objects['Building John Cabot University - Tiber Campus.001'], bpy.data.objects['Building58.001'], bpy.data.objects['Building59.001'], bpy.data.objects['Building60.001'], bpy.data.objects['Building61.001'], bpy.data.objects['Building62.001'], bpy.data.objects['Building63.001'], bpy.data.objects['Building64.001'], bpy.data.objects['Building65.001'], bpy.data.objects['Building66.001'], bpy.data.objects['Building67.001'], bpy.data.objects['Building68.001'], bpy.data.objects['Building69.001'], bpy.data.objects['Building70.001'], bpy.data.objects['Building Pizza Trilussa.001'], bpy.data.objects['Building71.001'], bpy.data.objects['Building72.001'], bpy.data.objects['Building73.001'], bpy.data.objects['Building74.001'], bpy.data.objects['Building75.001'], bpy.data.objects['Building76.001'], bpy.data.objects['Building77.001'], bpy.data.objects['Building78.001'], bpy.data.objects['Building79.001'], bpy.data.objects['Building80.001'], bpy.data.objects['Building81.001'], bpy.data.objects['Building82.001'], bpy.data.objects['Building83.001'], bpy.data.objects['Building84.001'], bpy.data.objects['Building85.001'], bpy.data.objects['Building86.001'], bpy.data.objects['Building87.001'], bpy.data.objects['Building88.001'], bpy.data.objects['Building89.001'], bpy.data.objects['Building90.001'], bpy.data.objects['Building Ospedale Israelitico Roma.001'], bpy.data.objects['Building Torre Caetani.001'], bpy.data.objects['Building91.001'], bpy.data.objects['Building Teatro di Marcello.001'], bpy.data.objects['Building92.001'], bpy.data.objects['Building Chiesa di San Nicola in Carcere.001'], bpy.data.objects['Building Chiesa di San Giovanni Calibita.001'], bpy.data.objects['Building93.001'], bpy.data.objects['Building94.001'], bpy.data.objects['Building95.001'], bpy.data.objects['Building96.001'], bpy.data.objects['Building97.001'], bpy.data.objects['Building98.001'], bpy.data.objects['Building99.001'], bpy.data.objects['Building Basilica di San Bartolomeo allIsola.001'], bpy.data.objects['Building100.001'], bpy.data.objects['Building101.001'], bpy.data.objects['Building102.001'], bpy.data.objects['Building103.001'], bpy.data.objects['Building104.001'], bpy.data.objects['Building105.001'], bpy.data.objects['Building106.001'], bpy.data.objects['Building107.001'], bpy.data.objects['Building108.001'], bpy.data.objects['Building Grattacheccaro Alla Fonte dOro.001'], bpy.data.objects['Building109.001'], bpy.data.objects['Building110.001'], bpy.data.objects['Building111.001'], bpy.data.objects['Building112.001'], bpy.data.objects['Building113.001'], bpy.data.objects['Building114.001'], bpy.data.objects['Building115.001'], bpy.data.objects['Building116.001'], bpy.data.objects['Building117.001'], bpy.data.objects['Building118.001'], bpy.data.objects['Building119.001'], bpy.data.objects['Building120.001'], bpy.data.objects['Building121.001'], bpy.data.objects['Building Chiesa di San Gregorio della Divina Pieta.001'], bpy.data.objects['SurfaceArea122.001'], bpy.data.objects['SurfaceArea123.001'], bpy.data.objects['SurfaceArea124.001']]
Processing object <bpy_struct, Object("Building0.001") at 0x000002E756A80808>
INFO: Found the Panda3D compatible Principled BSDF shader
INFO: tex-Plaster002_Color-1175447457309335745.png node is renamed to tex-Plaster002_Color-1175447457309335745.png
WARNING: Texture has no UV-INPUT! Building0.001 Base Color
INFO: Adding UV Map from the material: Building0.001
DIR is not exist: Creating...  C:\Users\andrea\Documents\tiber-river\walkintiber\thegame\tex
Texture:  tex-Plaster002_Color-1175447457309335745.png
RENDER IMAGE to C:\Users\andrea\Documents\tiber-river\walkintiber\thegame\tex\tex-Plaster002_Color-1175447457309335745.png; rel path: ./tex/tex-Plaster002_Color-1175447457309335745.png
COPY IMAGE C:\Users\andrea\Documents\tiber-river\walkintiber\thegame\asset_pipeline\input\buildings-test\test4_buildings.obj_textures\tex-Plaster002_Color-1175447457309335745.png to C:\Users\andrea\Documents\tiber-river\walkintiber\thegame\tex\tex-Plaster002_Color-1175447457309335745.png; rel path ./tex/tex-Plaster002_Color-1175447457309335745.png
Traceback (most recent call last):
  File "C:\Users\andrea\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\PRPEE-master\yabee_libs\egg_writer.py", line 1669, in write_out
    materials_str, USED_MATERIALS, USED_TEXTURES = get_egg_materials_str(selected_obj)
  File "C:\Users\andrea\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\PRPEE-master\yabee_libs\egg_writer.py", line 1363, in get_egg_materials_str
    used_textures.update(pbrtex.get_used_textures())
  File "C:\Users\andrea\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\PRPEE-master\yabee_libs\texture_processor.py", line 148, in get_used_textures
    if hasattr(bpy.context.object.active_material, "blend_method"):
AttributeError: 'NoneType' object has no attribute 'active_material'
```

As you can see something happened in terms of textures here, and the `.egg` file does have textures in the game (because of the `tex` directory blender made here. 

### Used modules

- [ ] [Egg Tree Parser](https://panda-utils.readthedocs.io/en/latest/egg-trees/introduction.html)
- [X] [Asset Pipeline](https://panda-utils.readthedocs.io/en/latest/asset-pipeline/introduction.html)
- [ ] [Asset Composer](https://panda-utils.readthedocs.io/en/latest/asset-pipeline/composer.html)

### Pipeline Command and relevant Egg file

```
python -m panda_utils.assetpipeline input/buildings-test test/models/buildings test/maps preblend blend2bam
```

**Comment by Wizzerinus** [comment]
Hi!

I believe this might be an issue with Blender, not a Panda Utils issue. It's common that the blender import/export process may give out warnings, while nothing wrong really happens. Generally I suppress most export warnings if the model works correctly in game.

Looking at it more, it seems that the model gets exported through PRPEE. The interesting thing about it, is that PRPEE should not run *at all* on this pipeline (since it's supposed to use panda3d-gltf). This is most likely a bug in PRPEE itself, or related to your Blender configuration. But also can be a bug in Panda Utils (although that seems unlikely). I will look into it more a bit later. Before I do though, you should apply [something like this patch](https://github.com/Toontown-Event-Horizon/YABEE/commit/9b0a870c53bfc90a1f6c7236172397d48a459685) to your installation because Panda Utils does not like when an unregister callback (which runs at the end of Blender's lifetime) causes Blender to crash.

Do note that PRPEE is not supported by the library, since RenderPipeline is unsupported (the recommended way to get similar results is something like `panda3d-complexpbr`), so I can only provide limited support for it.

**Comment by andreagalle** [comment]
Ok, thanks a lot for your additional explanations, but I think I need to better exaplain what I did: I wanted to compare the pipeline vs plain blender behaviour, to better understand what was going wrong with the textures and the `.obj` file I was importing:

1. Thus, PRPEE was not used through your panda utils pipeline, rather from the blender GUI.
2. Moreover, I was not worried by the warning, but rather I was concerned by the fact that neither the `.egg` nor the `.bam` file resulting from the pipeline, have textures once used into the game. Isent the `{texture-folder}` I am passing the one for the textures under your built directory? In that case it is always empty for me. 
3. Finally. if you need more details on reproducing my issue, just tell me whatever you need, but probably this [buildings-test.zip](https://github.com/Toontown-Event-Horizon/panda-utils/files/13404034/buildings-test.zip) is enough.

**Comment by Wizzerinus** [comment]
Okay I think I figured it out. The issue is happening because the textures are in a separate folder from the model itself. We never ran into this issue on our project, because we use Asset Composer which demands that it is not the case (only folders without subfolders are considered assets). This is therefore a bug on our side (the pipeline should not require such specifics), and will be probably fixed with Panda Utils 1.6, for now you can fix it by moving the files away from the `tex` folder and into the `buildings-test` folder.

**Comment by Wizzerinus** [comment]
This issue is a lot deeper than I expected. The export pipeline with `panda3d-gltf` (which is the default and misleadingly called `blend2bam`) does not patch texture paths, unlike `blend2bam`. So you'd imagine the solution is to add that procedure to `panda3d-gltf` export. However, we switched the default to `panda3d-gltf` precisely because `blend2bam` does not work correctly on Windows (a lot of the time no textures become imported). So it is theoretically possible it happens due to the texture patcher itself. I will do more tests before coming to a conclusion, though.

**Comment by andreagalle** [comment]
I tried it out, but now I got this error:

    (panda3D) PS C:\Users\andrea\Documents\tiber-river\walkintiber\thegame\asset_pipeline> python -m panda_utils.assetpipeline input/buildings-test test/models/buildings test/maps preblend blend2bam bam2egg egg2bam
    DEBUG:BlenderGIS-master.core.checkdeps:GDAL Python binding unavailable
    DEBUG:BlenderGIS-master.core.checkdeps:PyProj available
    DEBUG:BlenderGIS-master.core.checkdeps:Pillow available
    DEBUG:BlenderGIS-master.core.checkdeps:ImageIO Freeimage plugin available
    DEBUG:BlenderGIS-master.core.checkdeps:GDAL Python binding unavailable
    DEBUG:BlenderGIS-master.core.checkdeps:PyProj available
    DEBUG:BlenderGIS-master.core.checkdeps:Pillow available
    DEBUG:BlenderGIS-master.core.checkdeps:ImageIO Freeimage plugin available
    DEBUG:BlenderGIS-master.core.checkdeps:GDAL Python binding unavailable
    DEBUG:BlenderGIS-master.core.checkdeps:PyProj available
    DEBUG:BlenderGIS-master.core.checkdeps:Pillow available
    DEBUG:BlenderGIS-master.core.checkdeps:ImageIO Freeimage plugin available
    Buildings Test: Blender failed
    Traceback (most recent call last):
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_main
        return _run_code(code, main_globals, None,
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
        exec(code, run_globals)
      File "C:\Users\andrea\Documents\tiber-river\walkintiber\panda3D\Scripts\gltf2bam.exe\__main__.py", line 7, in <module>
      File "C:\Users\andrea\Documents\tiber-river\walkintiber\panda3D\lib\site-packages\gltf\cli.py", line 123, in main
        converter.update(gltf_data)
      File "C:\Users\andrea\Documents\tiber-river\walkintiber\panda3D\lib\site-packages\gltf\_converter.py", line 178, in update
        self.load_texture(texid, gltf_tex, gltf_data)
      File "C:\Users\andrea\Documents\tiber-river\walkintiber\panda3D\lib\site-packages\gltf\_converter.py", line 565, in load_texture
        uri = urllib.parse.unquote(uri)
    AttributeError: module 'urllib' has no attribute 'parse'

**Comment by Wizzerinus** [comment]
Known bug with new versions of `panda3d-gltf` (0.16 and up). Moguri (maintainer of panda3d-gltf) was unable to reproduce it and the tests don't fail for some reason so it is not fixed currently. You'd want to install `panda3d-gltf==0.15.0` to fix it.

Do note that the old versions misbehave when the path to the texture files contain spaces, so you should avoid that.

**Comment by andreagalle** [comment]
Now it works, but we still have an issue here. This is our input directory tree structure:

```
├───input
│
├─buildings
│   │      model-config.yml
│   │      test4_buildings.obj
│   │      test4_buildings.obj.mtl
│   │
│   └───test4_buildings.obj_textures
│              tex-Ground003_Color-5850203880815232605.png
│              tex-MarekCompositeWall00001_transparent-7939054643908036850.png
│              tex-Plaster002_Color-1175447457309335745.png
│              tex-RoofingTiles010_Color-6816502774111224903.png
│
└───roads
    │   test4_highways.obj
    │   test4_highways.obj.mtl
    │
    └───test4_highways.obj_textures
              tex-Asphalt010_Color-9762611950154616282.png
              tex-Concrete034_Color-11656647573067322145.png
              tex-Ground003_Color-7145765633138746005.png
              tex-KnerrKerb0001-9351530427465289062.png
              tex-PavingStones033_Color-12226304350843704997.png
              tex-PavingStones072_Color-8597493726302568772.png
              tex-road_marking_dash-15436948420208838439.png
```
Running the pipeline this way:
`python -m panda_utils.assetpipeline input/buildings buildings/models buildings/textures preblend blend2bam bam2egg egg2bam` results in the following error:
```
DEBUG:BlenderGIS-master.core.checkdeps:ImageIO Freeimage plugin available
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\andrea\Documents\tiber-river\walkintiber\panda3D\lib\site-packages\panda_utils\assetpipeline\__main__.py", line 77, in <module>
    main(util.get_debug(util.LoggingScope.PIPELINE))
  File "C:\Users\andrea\Documents\tiber-river\walkintiber\panda3D\lib\site-packages\panda_utils\assetpipeline\__main__.py", line 73, in main
    action(ctx, *args)
  File "C:\Users\andrea\Documents\tiber-river\walkintiber\panda3D\lib\site-packages\panda_utils\assetpipeline\models.py", line 446, in action_egg2bam
    shutil.copy(filename, copy_path)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\shutil.py", line 417, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'tex-RoofingTiles010_Color-6816502774111224903.png'
(panda3D) PS C:\Users\andrea\Documents\tiber-river\walkintiber\thegame\assets> 
```
while, moving all the `*.png` files at the same level of corresponding `*.obj` and `.obj.mtl` files resolves. Although this surprised me (since within the  `.obj.mtl` file the textures `*.png` files are referenced with the current path, like this `map_Ka test4_buildings.obj_textures/tex-Plaster002_Color-1175447457309335745.png`), do you think to move them would be the most "correct" solution or rather would you further patch this step?

I added a couple prints and this issue doesn't seem related to what you did in [your commit](https://github.com/Toontown-Event-Horizon/panda-utils/commit/3bb153061d221d89afedd6d056417d0b9fb6738a).

**Comment by Wizzerinus** [comment]
Yeah I'll also look into patching this today, sounds like it wasn't fully fixed

**Comment by Wizzerinus** [comment]
Confirmed this being a bug with egg2bam stage. I have a fix in my mind but I'll look at other steps that can inherit similar bugs

**Comment by andreagalle** [comment]
Wonderful! Thanks a lot. Last, but IFF i run the pipeline from within the same directory the `input` one is, everything's fine, but rather if I move one level up then `intermediate` and `built` directories are not made at the same level as the `input` one is (these directories are always created within the directory the pipeline is ran). Is that fine, or it is a good idea for you to generalize this? Of course is not an issue to run the pipeline from a specific point, but IF I want to run the pipeline programmatically, I think this would make the whole thing just more robust.

**Comment by Wizzerinus** [comment]
Okay so. The `input` folder is just a convention we use, pipeline doesn't actually care about the paths of your files. You can run it without any problems with any directory structure (except it does use built and intermediate for internal reasons, and script and bscript to hold user scripts if you need anything not in the main library). For example if you want you can do this
```
built
intermediate
asset1
asset2
...
```
I do not recommend making this but pipeline does not prevent you from doing so. If you want an enforced directory structure you should take a look at Asset Composer instead (wrapper around the pipeline), which enforces a structure for you and lets you rebuild assets on demand when anything inside that folder changes.

(Currently Asset Composer does not allow you to use subfolders with textures, but I can do something like "`model-config.yml` marks the folder as being an asset folder even if it has subfolders inside of it, or a more nuanced way of doing it if you have anything better in mind. Composer's documentation is also not the best atm but will be improved)

**Comment by andreagalle** [comment]
I will take a look at asset composer ASAP!

**Comment by Wizzerinus** [comment]
Alright I think I finished a version with a full fix to egg2bam. It is not tested on Windows yet as I don't run that operating system, so let me know if there are any problems. There probably will be something because path management is really hard to get right across all OS's, and some things I had to modify could not use pathlib in principle, but maybe everything will work (clueless).

**Comment by andreagalle** [comment]
Wonderful! We are going to test it on windows right now (yeah, we don't run it all the time, neither).

**Comment by andreagalle** [comment]
Yes it worked on windows! Are you going to freeze this version such that we can install it through PyPI or do you prefer not to release it yet?

**Comment by Wizzerinus** [comment]
I'll upload it when I have time, likely as stable 1.6. For now you'd have to install it from the commit.
